[package]
name = "solana_txn"
version = "0.2.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18.1"
solana-client = "1.18.1"
jito-geyser-protos = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }